In [1]:
import numpy as np

In [2]:
R = np.array([1, 0, 0, 0, 0]) # Полезные требования

In [3]:
# Матрица трассируемости требований на файлы исходного кода
Erf = np.array([[1, 0, 0, 0],
                [0.5, 0.5, 0, 0],
                [0, 0.5, 0.5, 0],
                [0, 0, 0.5, 0.5],
                [0, 0, 0, 1]])

In [4]:
# Матрица зависимостей между файлами исходного кода
Efd = np.array([[0, 0, 0, 0],
                [1, 0, 0, 0], # на файл № 2 имеется зависимость у файла № 1
                [0, 1, 0, 0],
                [0, 0, 0, 0]])

In [5]:
# Матрица распределения файлов по плагинам. Именно эти коэффициенты необходимо подобрать в работе
Efp = np.array([[1, 0, 0],
                [0, 1, 0],
                [0, 1, 0],
                [0, 0, 1]])

In [6]:
def activate(vec):
    for i in range(len(vec)):
        vec[i] = 1 if vec[i] > 0 else 0

In [7]:
def R_activate(vec):
    for i in range(len(vec)):
        vec[i] = 1 if vec[i] == 1 else 0

In [8]:
F = np.dot(R, Erf) # Задействованные файлы

In [9]:
F

array([1., 0., 0., 0.])

In [10]:
np.dot(Efd, np.dot(Efd, F))

array([0., 0., 1., 0.])

In [11]:
F = F + np.dot(Efd, F) # Задействованные файлы после разрешения зависимостей

In [12]:
activate(F) # Активация элементов слоя файлов

In [13]:
F

array([1., 1., 0., 0.])

In [14]:
P = np.dot(F, Efp) # Задействованные плагины

In [15]:
activate(P) # Активация элементов слоя плагинов

In [16]:
F_d = np.dot(Efp, P) # Вошедшие в поставку файлы исходного кода

In [17]:
activate(F_d) # Активация элементов слоя файлов

In [18]:
R_d = np.dot(Erf, F_d) # Вошедшие в поставку требования

In [19]:
R_activate(R_d) # Активация элементов слоя требований

In [20]:
R_d

array([1., 1., 1., 0., 0.])

In [21]:
K_un = (sum(R_d) - sum(R)) / (sum(R_d)) # Коэффициент бесполезности

In [22]:
'Коэффициент бесполезности в данной поставке = ' + str(int(round(K_un, 2) * 100)) + '%'

'Коэффициент бесполезности в данной поставке = 67%'