In [17]:
import numpy as np

In [100]:
from dependencies_calculator import DependenciesCalculator

In [26]:
n = 2

In [83]:
R = np.array([
    [1, 0],
    [1, 0],
    [0, 1]
])

In [84]:
U = np.zeros((2 ** n, n))

In [85]:
def bin_arr_to_dec_number(array):
    s_array = [str(el) for el in array]
    joined = ''.join(s_array)
    result = int(joined, 2)
    return result

In [86]:
def my_bin_arr_to_dec_number(array):
    length = len(array)
    result = 0
    for i in range(length):
        value = array[i]
        pow_value = length - (i + 1)
        term = value * (2 ** pow_value)
        result += term
    return result

In [90]:
for array in R:
    index = my_bin_arr_to_dec_number(array)
    U[index] = array

In [92]:
U

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [0., 0.]])

$$U_{\sum^{n}_{j = 1}(R_{i, n - j} \cdot 2^{n - j})} = R_{i}$$

In [94]:
T = np.array([
    [  1,   0,   0,   0],
    [0.5, 0.5,   0,   0],
    [  0, 0.5, 0.5,   0],
    [  0,   0, 0.5, 0.5],
    [  0,   0,   0,   1]
])

In [95]:
D = np.array([
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

In [96]:
m = np.shape(T)[1]

In [97]:
k = 3

In [104]:
R = np.array([
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 1, 0, 0]
])

array([[1. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0. ],
       [0. , 0.5, 0.5, 0. ]])

In [109]:
class DependenciesCalculator:
    def __init__(self, D, m):
        self.D = D
        self.m = m

    def calculate(self):
        D = self.D
        m = self.m

        shape = np.shape(D)
        deps = np.zeros(shape)
        deps = self.normalize_deps(deps)
        for j in range(m):
            dep = np.linalg.matrix_power(D, j)
            dep = self.normalize_deps(dep)
            deps += dep
        deps = self.normalize_deps(deps)
        return deps

    def normalize_deps(self, deps):
        f_in = lambda x: 0 if x == 0 else 1
        result = [[f_in(el) for el in row] for row in deps]
        return np.array(result)

In [125]:
def convert(fun, mtx):
    result = np.zeros(np.shape(mtx))

    for i in range(len(mtx)):
        for j in range(len(mtx[i])):
            el = mtx[i][j]
            value = fun(el)
            result[i][j] = value
    
    return result

In [126]:
def f_in(mtx):
    fun = lambda x: 0 if x == 0 else 1
    return convert(fun, mtx)

In [127]:
def f_im(mtx):
    fun = lambda x: 0 if x < 1 else 1
    return convert(fun, mtx)

In [128]:
deps_calculator = DependenciesCalculator(D, m)

In [129]:
sum_D = deps_calculator.calculate()

In [130]:
X = np.array([[1., 0., 0.],
              [0., 0., 1.],
              [1., 0., 0.],
              [0., 0., 1.]])

In [136]:
F = R.dot(T)
F

array([[1. , 0. , 0. , 0. ],
       [0.5, 0.5, 0. , 0. ],
       [0. , 0.5, 0.5, 0. ]])

In [137]:
F = F.dot(sum_D)
F

array([[1. , 0. , 1. , 0. ],
       [0.5, 0.5, 1. , 0.5],
       [0. , 0.5, 1. , 0.5]])

In [138]:
P = F.dot(X)
P

array([[2. , 0. , 0. ],
       [1.5, 0. , 1. ],
       [1. , 0. , 1. ]])

In [139]:
P = f_in(P)
P

array([[1., 0., 0.],
       [1., 0., 1.],
       [1., 0., 1.]])

In [142]:
P.T

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 1., 1.]])