In [1]:
import pygad
import numpy as np

In [2]:
from cost_calculator import CostCalculator

In [3]:
# function_inputs = [1,1,1,1,1]
desired_output = -1

In [4]:
l = 1
n = 5
m = 4
k = 3

In [5]:
M = 10**6

In [6]:
T = np.array([
    [  1,   0,   0,   0],
    [0.5, 0.5,   0,   0],
    [  0, 0.5, 0.5,   0],
    [  0,   0, 0.5, 0.5],
    [  0,   0,   0,   1]
])

In [7]:
D = np.array([
    [0, 0, 1, 0],
    [0, 0, 1, 1],
    [0, 0, 0, 0],
    [0, 0, 0, 0]
])

In [8]:
C = np.array([
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1],
    [1, 1, 1, 1, 1]
])

In [9]:
E = np.array([
    [1, 0, 0, 0, 0]
])

In [10]:
def fitness_func(ga_instance, solution, solution_idx):
    A = np.reshape(solution, (m, k))

    cost_calculator = CostCalculator(T, D, C, E, A)
    output = cost_calculator.calculate()
    
    for row in A:
        if np.sum(row) != 1:
            output = M
    
    
    fitness = 1.0 / (np.abs(output - desired_output) + 1 / M)
    return fitness

In [11]:
fitness_function = fitness_func

num_generations = 50
num_parents_mating = 4

sol_per_pop = 8
num_genes = m * k

init_range_low = 0 # нижняя граница
init_range_high = 1 + 1 # 1 - верхняя граница, +1 - чтоб работало

parent_selection_type = "sss"
keep_parents = 1

crossover_type = "single_point"

mutation_type = "random"
mutation_percent_genes = 10

In [12]:
ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating,
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop,
                       num_genes=num_genes,
                       init_range_low=init_range_low,
                       init_range_high=init_range_high,
                       parent_selection_type=parent_selection_type,
                       keep_parents=keep_parents,
                       crossover_type=crossover_type,
                       mutation_type=mutation_type,
                       mutation_percent_genes=mutation_percent_genes,
                       gene_type = [int for i in range(num_genes)])

/home/dambr/venv/lib/python3.12/site-packages/pygad/pygad.py:1139: UserWarning: The 'delay_after_gen' parameter is deprecated starting from PyGAD 3.3.0. To delay or pause the evolution after each generation, assign a callback function/method to the 'on_generation' parameter to adds some time delay.
  warnings.warn("The 'delay_after_gen' parameter is deprecated starting from PyGAD 3.3.0. To delay or pause the evolution after each generation, assign a callback function/method to the 'on_generation' parameter to adds some time delay.")


In [13]:
ga_instance.run()

In [14]:
solution, solution_fitness, solution_idx = ga_instance.best_solution()
A = np.reshape(solution, (m, k))
print("Parameters of the best solution")
print(A)
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))

cost_calculator = CostCalculator(T, D, C, E, A)
cost = cost_calculator.calculate()
print('cost', cost)

Parameters of the best solution
[[0 0 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Fitness value of the best solution = 0.09999999000000101
cost 9
